# Generated by Django 5.2.12 on 2026-03-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('kana', models.CharField(max_length=100, verbose_name='かな')),
                ('birthday', models.DateField(verbose_name='誕生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', 'その他')], max_length=10, verbose_name='性別')),
                ('classroom', models.CharField(max_length=50, verbose_name='クラス')),
            ],
            options={
                'verbose_name': '園児',
                'verbose_name_plural': '園児',
                'ordering': ['classroom', 'kana', 'name'],
            },
        ),
    ]
