# Generated by Django 5.2.12 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nursery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="children",
            name="is_absent",
            field=models.BooleanField(default=False, verbose_name="欠席"),
        ),
    ]

