# Generated by Django 5.2.12 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nursery", "0002_children_is_absent"),
    ]

    operations = [
        migrations.AddField(
            model_name="children",
            name="absence_reason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="欠席理由"
            ),
        ),
    ]

