# Generated by Django 5.2.12 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nursery", "0003_children_absence_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="children",
            name="facility_id",
            field=models.CharField(default="1", max_length=50, verbose_name="施設ID"),
        ),
        migrations.AddField(
            model_name="children",
            name="class_id",
            field=models.CharField(default="1", max_length=50, verbose_name="クラスID"),
        ),
        migrations.AddField(
            model_name="children",
            name="sub_class_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="サブクラスID"
            ),
        ),
    ]

