# Generated by Django 5.2.12 on 2026-03-27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("nursery", "0005_remove_children_classroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now, verbose_name="日付")),
                ("is_absent", models.BooleanField(default=True, verbose_name="欠席")),
                ("reason", models.CharField(blank=True, default="", max_length=255, verbose_name="欠席理由")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="nursery.children",
                    ),
                ),
            ],
            options={
                "verbose_name": "出席",
                "verbose_name_plural": "出席",
                "ordering": ["-date", "child__class_id", "child__kana", "child__name"],
            },
        ),
        migrations.RemoveField(
            model_name="children",
            name="absence_reason",
        ),
        migrations.RemoveField(
            model_name="children",
            name="is_absent",
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(fields=("child", "date"), name="uniq_attendance_child_date"),
        ),
    ]

