# Generated by Django 5.2.12 on 2026-03-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0006_attendance_model_and_remove_children_absence_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='children',
            options={'ordering': ['class_id', 'kana', 'name'], 'verbose_name': '園児', 'verbose_name_plural': '園児'},
        ),
    ]
