# Generated by Django 5.2.12 on 2026-04-03
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nursery", "0007_alter_children_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_late",
            field=models.BooleanField(default=False, verbose_name="遅刻"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_early_leave",
            field=models.BooleanField(default=False, verbose_name="早退"),
        ),
    ]

