# Generated by Django 5.2.12 on 2026-04-03
from django.db import migrations, models


def forwards_set_attendance_status(apps, schema_editor):
    Attendance = apps.get_model("nursery", "Attendance")

    for row in Attendance.objects.all().only(
        "id", "is_absent", "is_late", "is_early_leave"
    ):
        # 優先度は遅刻/早退→欠席の順（同時に立つケースは想定しない）
        if getattr(row, "is_late", False):
            row.attendance_status = 1
        elif getattr(row, "is_early_leave", False):
            row.attendance_status = 2
        elif getattr(row, "is_absent", False):
            row.attendance_status = 3
        else:
            row.attendance_status = None
        row.save(update_fields=["attendance_status"])


class Migration(migrations.Migration):
    dependencies = [
        ("nursery", "0008_add_late_and_early_leave_to_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="attendance_status",
            field=models.IntegerField(
                blank=True,
                null=True,
                choices=[
                    (1, "遅刻"),
                    (2, "早退"),
                    (3, "欠席"),
                ],
                verbose_name="出欠状況",
            ),
        ),
        migrations.RunPython(forwards_set_attendance_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="attendance",
            name="is_absent",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="is_late",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="is_early_leave",
        ),
    ]

